version: '3'

services:
  postgresdb:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: 'hubr-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=hubr'
    ports:
      - "5432:5432"
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data:z
    depends_on:
      - app
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'hubr'
    ports:
      - '8080:8080'
