version: '3'

services:
  postgresdb:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: 'hubr-postgres'
    ports:
      - "5432:5432"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'hubr'
    ports:
      - '8080:8080'
